src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $creation_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $modification_date = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?Topic $topic = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getCreationDate(): ?\DateTime
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTime $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getModificationDate(): ?\DateTime
    {
        return $this->modification_date;
    }

    public function setModificationDate(?\DateTime $modification_date): static
    {
        $this->modification_date = $modification_date;

        return $this;
    }

    public function getTopic(): ?Topic
    {
        return $this->topic;
    }

    public function setTopic(?Topic $topic): static
    {
        $this->topic = $topic;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use App\Entity\Topic;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('message')
            // ->add('creation_date')
            // ->add('modification_date')
            // ->add('topic', EntityType::class, [
            //      'class' => Topic::class,
            //      'choice_label' => 'id',
            // ])
            // ->add('user', EntityType::class, [
            //      'class' => User::class,
            //      'choice_label' => 'id',
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Topic;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/comment')]
final class CommentController extends AbstractController
{
    #[Route(name: 'app_comment_index', methods: ['GET'])]
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    #[Route('/new/{topicId}', name: 'app_comment_new', methods: ['GET', 'POST'])]
    public function new(int $topicId, Request $request, EntityManagerInterface $entityManager): Response
    {
        // Récupérer le topic correspondant
        $topic = $entityManager->getRepository(Topic::class)->find($topicId);

        if (!$topic) {
            throw $this->createNotFoundException("Topic non trouvé !");
        }
        // Créer le commentaire
        $comment = new Comment();
        $comment->setTopic($topic); // associer le topic ici

        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Associe l'utilisateur au commentaire
            $comment->setUser($this->getUser());
            // Définit la date de création
            $comment->setCreationDate(new \DateTime());


            $entityManager->persist($comment);
            $entityManager->flush();

            $topic = $comment->getTopic();

            // Redirige vers la page du Topic (app_topic_show)
            return $this->redirectToRoute('app_topic_show', [
                'id' => $topic->getId(),  // Passe l'ID du Topic à la route
            ], Response::HTTP_SEE_OTHER);
        };

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_show', methods: ['GET'])]
    public function show(Comment $comment): Response
    {
        return $this->render('comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_delete', methods: ['POST'])]
    public function delete(Request $request, Comment $comment, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $comment->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comment/_delete_form.html.twig
<form method="post" action="{{ path('app_comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/comment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning m-2">{{ button_label|default('Envoyer') }}</button>
{{ form_end(form) }}

templates/comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comment{% endblock %}

{% block body %}
    <h1>Modifier commentaire</h1>

    {% if app.user %}

        {{ include('comment/_form.html.twig', {'button_label': 'Modifier'}) }}

        {{ include('comment/_delete_form.html.twig') }}

    {% endif %}
{% endblock %}

templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment index{% endblock %}

{% block body %}
    <h1>Les commentaires</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Message</th>
                <th>Date de création</th>
                <th>Date de modification</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.message }}</td>
                <td>{{ comment.creationDate ? comment.creationDate|date('Y-m-d') : '' }}</td>
                <td>{{ comment.modificationDate ? comment.modificationDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a class="btn btn-dark" href="{{ path('app_comment_show', {'id': comment.id}) }}">Voir +</a>
                    <a class="btn btn-danger" href="{{ path('app_comment_delete', {'id': comment.id}) }}">Supprimer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Pas de commentaire trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <h1>Création d'un nouveau commentaire</h1>

    <div class="container log register">
        {{ include('comment/_form.html.twig') }}
    </div>
{% endblock %}

templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment{% endblock %}

{% block body %}
    <h1>Un commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Message</th>
                <td>{{ comment.message }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ comment.creationDate ? comment.creationDate|date('d-m-Y') : '' }}</td>
            </tr>
            <tr>
                <th>Modification_date</th>
                <td>{{ comment.modificationDate ? comment.modificationDate|date('d-m-Y') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-dark" href="{{ path('app_comment_index') }}">Retour</a>

     {% if app.user and app.user == comment.user %}
        <a class="btn btn-warning" href="{{ path('app_comment_edit', {'id': comment.id}) }}">Modifier</a>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') or app.user == comment.user %}
        {{ include('comment/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}